### ISSUE TITLE
Error / Not able to log in with admin/admin or user/user

### ISSUE THREAD

**Issue by connecteev** [pacoorozco/gamify-l5#44]
**Issue**
Not able to log in with admin/admin or user/user after fresh installation.

**Desktop:**
 - OS: MacOS
 - Browser: Chrome

**Steps to reproduce the behavior:**
Go through the steps here: https://github.com/pacoorozco/gamify-l5#local-server-method
Then run ```php artisan serve --port=8000```
Then go to http://127.0.0.1:8000/login and enter credentials (admin/admin or user/user)
Login is not accepted. See error ("These credentials do not match our records.") below.

**Screenshots**
See https://prnt.sc/o232wz

Also, do we *need* to run ```php -S localhost:8080 -t public```
or is running ```php artisan serve --port=8000``` enough?

**Comment by connecteev** [comment]
Ok, turns out it works if you use the email instead of username, like
admin@example.com

The README needs to be fixed.

**Comment by pacoorozco** [comment]
You are right, sorry :man_facepalming:
