### ISSUE TITLE
Cannot answer questions / play 

### ISSUE THREAD

**Issue by connecteev** [pacoorozco/gamify-l5#45]
Create a question from the Admin, make sure it is published, and then go to the front end to 'play' the game: http://127.0.0.1:8000/questions. 

Select the question. Going to a question gives an error:
http://127.0.0.1:8000/questions/damn

Error: "Sorry, the page you are looking for could not be found."

I don't think https://github.com/pacoorozco/gamify-l5/issues/7 has been fixed.

**Comment by pacoorozco** [comment]
Hi @connecteev 

It was a routing error, not related with  #7 . It was produced by  #37.

There are no test in the code :crying_cat_face: I should invest some time to add them,

Thanks

**Comment by connecteev** [comment]
Thanks @pacoorozco for the responsiveness!
After a git pull I am still seeing "Sorry, the page you are looking for could not be found."
when I go to http://127.0.0.1:8000/questions/whats-your-name

Btw, I have some ideas for enhancing this package further, if you are going to maintain it let me know and I'd be happy to contribute more ideas into the issues list as enhancements.
