### ISSUE TITLE
Admin: I can't create Answer choices when creating a new Question

### ISSUE THREAD

**Issue by eampudia** [pacoorozco/gamify-l5#5]
When creating a new questiong, it's not possible to create Answer choices, you have to save it a re-edit again.

**Comment by eampudia** [comment]
ENHANCEMENT????? sure???

**Comment by pacoorozco** [comment]
Hi @eampudia 
At this moment you must save the question, the edit it again and add choices and actions.
I'm sure there is a better way to do this, I'm working on it :-D
Thanks

**Comment by pacoorozco** [comment]
Working on it, branch issue-5
